language: python
python:
- '2.7'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- python setup.py install
- sudo apt-get install pandoc
script:
- pytest --cov ebadge/ tests
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then codecov; fi
- "./publish.sh"
env:
  global:
    secure: bLwlifBXpeWhvwne1mvRFbyJoodOeb6x3TJxqlHbdDjOzUj6SZOiMznj906cqavse8z9WxwEzcKFAnoTBn04LVc2e6JEa5oXKyN3VzZaO9lHniFBrKF6JxbNRm6jUMZXxmCLrHm8XZXxLeFLgoH+LGhmMhJW2Ce9vhTYumvpWityCQ5fabsZvoytGpFSJQ8THbUfL3654LuxaziEFB0M2LA1inIqx4Yx3ENfCsxoB6RNveA0eG7SdF2hywnF97pU8VgkmATOzpeUvw8a91c/pjezPea6g2MSTtnD6/qYMZ2EPzyeLjOvN179PgsRBI9/s9TLKYrUiB1Rqo+b49hyoIXC7wMwVRAsAghnwY1kduzRWqm/8IJTQ1C+SNQ9/WkptEooc2MpGbWhxW2XjB5eZv4s4vtezJs0+bL2V0ITUGM5Nzn1vImysBZWR8Tr+DZwN1ipDo+lieD4K/1vM0jOYx4RouAnQRyrq7v5IU7ClPod6D02uO7SyK2UWwXPesov81yWEYdC2kwYIKOLKu4Sdbu3k4E2qlmFAYO14TZ7CgPeBulVN7d+z1vQvozzYZd1NIYcZ535FS0LUwl41JPfvniHwBalTrnJYw5zjjv7mZF6PuORmkrDG+lqz0eOJGnyw5+d+PBYXMLiifysGrohFUS79iZw+LZJPg+HAIGDPqU=
