# sudo: false # based on codecov to speed up the build, https://github.com/codecov/example-python/blob/master/.travis.yml

language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py install
  - sudo apt-get install pandoc
script:
  - pytest --cov ebadge/ tests
after_success:
  - codecov
  - ./publish.sh